#!/bin/bash
#
# PreToolUse Hook: Validate Write paths for loop-with-codex-review
#
# Blocks Claude from writing to:
# - Todos files (should use native TodoWrite instead)
# - Prompt files (read-only, generated by Codex)
# - Wrong round number summary files
# - Summary files outside .gaac-loop.local/
# - Goal tracker after Round 0
#

set -euo pipefail

# Load shared functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/loop-common.sh"

# ========================================
# Parse Hook Input
# ========================================

HOOK_INPUT=$(cat)
TOOL_NAME=$(echo "$HOOK_INPUT" | jq -r '.tool_name // ""')

if [[ "$TOOL_NAME" != "Write" ]]; then
    exit 0
fi

FILE_PATH=$(echo "$HOOK_INPUT" | jq -r '.tool_input.file_path // ""')
FILE_PATH_LOWER=$(to_lower "$FILE_PATH")

# ========================================
# Block Todos and Prompt Files
# ========================================

if is_round_file_type "$FILE_PATH_LOWER" "todos"; then
    todos_blocked_message "Write" >&2
    exit 2
fi

if is_round_file_type "$FILE_PATH_LOWER" "prompt"; then
    prompt_write_blocked_message >&2
    exit 2
fi

# ========================================
# Determine File Types
# ========================================

IS_SUMMARY_FILE=false
if is_round_file_type "$FILE_PATH_LOWER" "summary"; then
    IS_SUMMARY_FILE=true
fi

IN_GAAC_LOOP_DIR=false
if echo "$FILE_PATH" | grep -q '\.gaac-loop\.local/'; then
    IN_GAAC_LOOP_DIR=true
fi

# If not a summary file and not in .gaac-loop.local, allow normally
if [[ "$IS_SUMMARY_FILE" == "false" ]] && [[ "$IN_GAAC_LOOP_DIR" == "false" ]]; then
    exit 0
fi

# For state.md and goal-tracker.md in .gaac-loop.local, we need further validation
# For other files in .gaac-loop.local that aren't summaries, allow them
if [[ "$IN_GAAC_LOOP_DIR" == "true" ]] && [[ "$IS_SUMMARY_FILE" == "false" ]]; then
    if ! echo "$FILE_PATH_LOWER" | grep -qE '(state|goal-tracker)\.md$'; then
        exit 0
    fi
fi

# ========================================
# Find Active Loop and Current Round
# ========================================

PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
LOOP_BASE_DIR="$PROJECT_ROOT/.gaac-loop.local"
ACTIVE_LOOP_DIR=$(find_active_loop "$LOOP_BASE_DIR")

if [[ -z "$ACTIVE_LOOP_DIR" ]]; then
    exit 0
fi

CURRENT_ROUND=$(get_current_round "$ACTIVE_LOOP_DIR/state.md")

# ========================================
# Block Goal Tracker After Round 0
# ========================================

if echo "$FILE_PATH" | grep -qE 'goal-tracker\.md$' && [[ "$CURRENT_ROUND" -gt 0 ]]; then
    SUMMARY_FILE="$ACTIVE_LOOP_DIR/round-${CURRENT_ROUND}-summary.md"
    cat >&2 << EOF
# Goal Tracker Write Blocked (Round ${CURRENT_ROUND})

After Round 0, only Codex can modify the Goal Tracker.

**To request changes**, document them in your summary:
\`$SUMMARY_FILE\`

Use this format:
\`\`\`markdown
## Goal Tracker Update Request

### Requested Changes:
- [Describe what should be changed]

### Justification:
[Explain why this change is needed]
\`\`\`
EOF
    exit 2
fi

# ========================================
# Block Summary Files Outside .gaac-loop.local
# ========================================

if [[ "$IS_SUMMARY_FILE" == "true" ]] && [[ "$IN_GAAC_LOOP_DIR" == "false" ]]; then
    CORRECT_PATH="$ACTIVE_LOOP_DIR/round-${CURRENT_ROUND}-summary.md"
    cat >&2 << EOF
# Wrong Summary Location

Summary files MUST be in the loop directory.

**Correct path**: \`$CORRECT_PATH\`
EOF
    exit 2
fi

# ========================================
# Extract Path Components
# ========================================

CLAUDE_FILENAME=""
if [[ "$FILE_PATH" =~ \.gaac-loop\.local/[^/]+/(.+)$ ]]; then
    CLAUDE_FILENAME="${BASH_REMATCH[1]}"
elif [[ "$FILE_PATH" =~ \.gaac-loop\.local/(.+)$ ]]; then
    CLAUDE_FILENAME="${BASH_REMATCH[1]}"
else
    exit 0
fi

# ========================================
# Validate Round Number (for summary files)
# ========================================

if [[ "$IS_SUMMARY_FILE" == "true" ]]; then
    CLAUDE_ROUND=$(extract_round_number "$CLAUDE_FILENAME")

    if [[ -n "$CLAUDE_ROUND" ]] && [[ "$CLAUDE_ROUND" != "$CURRENT_ROUND" ]]; then
        CORRECT_PATH="$ACTIVE_LOOP_DIR/round-${CURRENT_ROUND}-summary.md"
        cat >&2 << EOF
# Wrong Round Number

You are trying to write to \`round-${CLAUDE_ROUND}-summary.md\`, but the current round is **${CURRENT_ROUND}**.

**Correct path**: \`$CORRECT_PATH\`

Do NOT increment the round number yourself.
EOF
        exit 2
    fi
fi

# ========================================
# Validate Directory Path
# ========================================

CORRECT_PATH="$ACTIVE_LOOP_DIR/$CLAUDE_FILENAME"

if [[ "$FILE_PATH" != "$CORRECT_PATH" ]]; then
    cat >&2 << EOF
# Wrong Directory Path

You are trying to write to: \`$FILE_PATH\`
Correct path: \`$CORRECT_PATH\`
EOF
    exit 2
fi

exit 0
